FROM python:3.9-slim

WORKDIR /app

COPY ServerCode/ .

RUN pip install Flask

RUN pip install -r mockapp/requirements.txt

EXPOSE 5000

ENV FLASK_APP=application/AppServer.py
ENV FLASK_RUN_HOST=0.0.0.0

CMD ["flask", "run"]


