name: BubbleScan Release

on:
  push:
    branches:
      - AutomateWorkflow109 #change branch to main after testing

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Make script executable
        run: chmod +x BubbleScan.sh

      - name: Run BubbleScan script
        run: ./BubbleScan.sh

      - name: Archive executable and static files
        run: zip -r dist/Bubblescan.zip ServerCode/dist/AppServer.exe ServerCode/dist/static

      - name: Create a new Git tag
        id: create_tag
        run: |
          TAG="v$(date +'%Y%m%d%H%M%S')"
          echo "TAG=$TAG" >> $GITHUB_ENV
          git tag $TAG
          git push origin $TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ServerCode/dist/Bubblescan.zip
          tag_name: ${{ env.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
