name: BubbleScan Mac Release

on:
  push:
    branches:
      - issue124MacOS

jobs:
  build-macos:
    runs-on: macos-latest

    permissions:
      contents: write  

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install build tools for scipy
        run: brew install gcc openblas lapack

      - name: Upgrade pip, setuptools, and wheel
        run: pip install --upgrade pip setuptools wheel

      - name: Set executable permissions for BubbleScan.sh
        run: chmod +x BubbleScan.sh

      - name: Run BubbleScan script
        shell: bash
        run: ./BubbleScan.sh

      - name: List files in ServerCode/dist after running BubbleScan.sh
        run: ls -l ServerCode/dist || echo "ServerCode/dist not found"

      - name: Verify BubbleScan exists
        shell: bash
        run: |
          if [ -f "ServerCode/dist/BubbleScan-macOS" ]; then
              echo "BubbleScan found in ServerCode/dist."
          else
              echo "BubbleScan not found in ServerCode/dist."
              exit 1
          fi

      - name: Zip files for release
        shell: bash
        run: |
          zip -r ServerCode/dist/BubbleScan.zip ServerCode/dist/BubbleScan-macOS ServerCode/dist/static

      - name: Create a new Git tag for macOS
        id: create_tag
        shell: bash
        run: |
          TAG="v$(date +'%Y%m%d%H%M%S')-macOS"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "::set-output name=TAG::$TAG"
          git tag $TAG
          git push origin $TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Upload macOS binary to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ServerCode/dist/BubbleScan.zip
          tag_name: ${{ steps.create_tag.outputs.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}