name: BubbleScan Release

on:
  push:
    branches:
      - AutomateWorkflow109 #change branch to main after testing

jobs:
  build-windows:
    runs-on: windows-latest

    permissions:
      contents: write  

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Run BubbleScan script
        shell: bash
        run: ./BubbleScan.sh

      - name: List files in ServerCode/dist after running BubbleScan.sh
        run: ls -l ServerCode/dist || echo "ServerCode/dist not found"

      - name: Verify BubbleScan exists
        shell: bash
        run: |
          if [ -f "ServerCode/dist/BubbleScan-Windows.exe" ]; then
              echo "BubbleScan found in ServerCode/dist."
          else
              echo "BubbleScan not found in ServerCode/dist."
              exit 1
          fi

      - name: Zip files for release
        run: |
          Compress-Archive -Path ServerCode/dist/BubbleScan-Windows.exe, ServerCode/dist/static -DestinationPath ServerCode/dist/BubbleScan.zip
        shell: powershell
        
      - name: Create a new Git tag with date and time for Windows
        id: create_tag
        shell: powershell
        run: |
          # Generate a timestamp-based tag
          $Tag = "v$(Get-Date -Format 'yyyyMMddHHmmss')-Windows"

          # Output the new tag
          echo "New tag: $Tag"
          echo "TAG=$Tag" | Out-File -FilePath $env:GITHUB_ENV -Append

          # Create and push the new tag
          git tag $Tag
          git push origin $Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  build-macos:
    runs-on: macos-latest

    permissions:
      contents: write  

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Set executable permissions for BubbleScan.sh
        run: chmod +x BubbleScan.sh

      - name: Run BubbleScan script
        shell: bash
        run: ./BubbleScan.sh

      - name: List files in ServerCode/dist after running BubbleScan.sh
        run: ls -l ServerCode/dist || echo "ServerCode/dist not found"

      - name: Verify BubbleScan exists
        shell: bash
        run: |
          if [ -f "ServerCode/dist/BubbleScan-macOS" ]; then
              echo "BubbleScan found in ServerCode/dist."
          else
              echo "BubbleScan not found in ServerCode/dist."
              exit 1
          fi

      - name: Zip files for release
        shell: bash
        run: |
          zip -r ServerCode/dist/BubbleScan.zip ServerCode/dist/BubbleScan-macOS ServerCode/dist/static

      - name: Create a new Git tag with date and time for macOS
        id: create_tag
        shell: bash
        run: |
          # Generate a timestamp-based tag
          TAG="v$(date +'%Y%m%d%H%M%S')-macOS"

          # Output the new tag
          echo "New tag: $TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV

          # Create and push the new tag
          git tag "$TAG"
          git push origin "$TAG"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ServerCode/dist/BubbleScan.zip
          tag_name: ${{ steps.create_tag.outputs.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
